### ISSUE TITLE
MiniMap image Location Error

### ISSUE THREAD

**Issue by raghul1129** [damirporobic/UE4_Minimap#2]
minimap is working good,my image image for the minimap is not moved properly,i have set the image size in the create widget,what is that level dimension ,how to add that i have seen wiki also i cant understand that .

**Comment by DamirPorobic** [comment]
Can you post a top view Screenshot of your map and a screenshot of creating the widget with settings,  im interested in seeing what parameters that you have set.

**Comment by Rko619** [comment]
i have set the texture size correct , what i dint know is the level dimension?
![dadfa](https://cloud.githubusercontent.com/assets/20899479/17553766/5c26548a-5f25-11e6-9b44-b54d88580b99.PNG)
![hop](https://cloud.githubusercontent.com/assets/20899479/17553767/5c280b40-5f25-11e6-8bb0-b01f9f81c1bc.PNG)

**Comment by DamirPorobic** [comment]
Ok, let's presume your texture is covering the area like on this screenshot (remember, your texture must be centered at the x=0 and y=0 of the UE4 Level.

![screenshot_20160810_152108](https://cloud.githubusercontent.com/assets/12796236/17555946/d1d1c3e0-5f11-11e6-8804-a419506b4478.png)

The level dimension is the width between the red arrow. It could be tricky to find the correct width, you could place some dummy actor at the most left part of the area that the texture is covering, then, check his location on the X axis, take the value and multiply by 2. If the actor is located at x=2000, z=100, z=0 then you level dimension would be 2000 \* 2 = 4000. Does that make sense?

**Comment by raghul1129** [comment]
can you explain this in a simpler manner?

**Comment by DamirPorobic** [comment]
You have a texture that represents some portion of the ue4 space,  you are not covering all ue4 space that there is,  only a portion that is interesting for your game. The texture that you have is not probably a 1:1 representation of your ue4 space,  thats why we need the texture size and the size of the map that the texture represents so that we can calculate the proportion.  

Back to the example,  create any actor,  place it at x=0 y=0 and z=0, then move this actor in ue4 space down the x axis (positiv or negative),  as far as your map goes,  check what the x value is,  multiply it by 2 and use this value.

**Comment by raghul1129** [comment]
Thanks i got that working :).

**Comment by DamirPorobic** [comment]
cool, glad to hear that :)
